# Copyright 2020 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Launch many of the simple node in a component container."""

import launch
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode


def generate_launch_description():
    """Generate launch description with multiple components."""

    container = ComposableNodeContainer(
            name='many_nodes',
            namespace='',
            package='rclcpp_components',
            node_executable='component_container',
            composable_node_descriptions=[
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node00'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node01'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node02'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node03'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node04'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node05'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node06'),
                # Above works without any connext changes
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node07'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node08'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node09'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node10'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node11'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node12'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node13'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node14'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node15'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node16'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node17'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node18'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node19'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node20'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node21'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node22'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node23'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node24'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node25'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node26'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node27'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node28'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node29'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node30'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node31'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node32'),
                # Above works with max_objects_per_thread set to 4096
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node33'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node34'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node35'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node36'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node37'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node38'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node39'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node40'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node41'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node42'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node43'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node44'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node45'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node46'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node47'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node48'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node49'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node50'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node51'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node52'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node53'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node55'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node55'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node56'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node57'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node58'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node59'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node60'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node61'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node62'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node63'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node66'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node65'),
                ComposableNode(
                    package='many_nodes',
                    plugin='many_nodes::SimpleNode',
                    namespace='/node66'),
                # Above works with max_objects_per_thread set to 8192
            ],
            output='both',
    )

    return launch.LaunchDescription([container])
